Repository web3j/web3j, pull requests merged in 2018-11, with the labels that each got.

#773 718: Added support for CLEARTEXT communication.
  core/src/main/java/org/web3j/protocol/http/HttpService.java
Labels: bug, needs-ci-approvals

#776 Allow using java keywords as solidity function names
  codegen/src/main/java/org/web3j/codegen/SolidityFunctionWrapper.java
  codegen/src/test/java/org/web3j/codegen/SolidityFunctionWrapperGeneratorTest.java
  codegen/src/test/resources/solidity/build.sh
  codegen/src/test/resources/solidity/misc/Misc.sol
  codegen/src/test/resources/solidity/misc/build/Misc.abi
  codegen/src/test/resources/solidity/misc/build/Misc.bin
Labels: needs-review

#713 Fix invalid index error on node disconnection.
  core/src/main/java/org/web3j/protocol/core/DefaultBlockParameter.java
Labels: needs-ci-approvals

#792 Feature/767 pantheon rpc
  pantheon/build.gradle
  pantheon/src/main/java/org/web3j/protocol/pantheon/JsonRpc2_0Pantheon.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/Pantheon.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/response/FullDebugTraceInfo.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/response/PantheonEthAccountsMapResponse.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/response/PantheonFullDebugTraceResponse.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/response/StructLogs.java
  pantheon/src/test/java/org/web3j/protocol/pantheon/RequestTest.java
  pantheon/src/test/java/org/web3j/protocol/pantheon/ResponseTest.java
  settings.gradle
Labels: needs-ci-approvals

#791 Feature/768 pubsub docs
  docs/source/getting_started.rst
Labels: needs-ci-approvals

#794 Merge release/4.0 back onto master
  codegen/src/main/java/org/web3j/codegen/SolidityFunctionWrapper.java
  codegen/src/test/java/org/web3j/codegen/SolidityFunctionWrapperGeneratorTest.java
  codegen/src/test/resources/solidity/build.sh
  codegen/src/test/resources/solidity/misc/Misc.sol
  codegen/src/test/resources/solidity/misc/build/Misc.abi
  codegen/src/test/resources/solidity/misc/build/Misc.bin
  core/build.gradle
  core/src/main/java/org/web3j/crypto/Bip44WalletUtils.java
  core/src/main/java/org/web3j/crypto/Wallet.java
  core/src/main/java/org/web3j/crypto/WalletFile.java
  core/src/main/java/org/web3j/crypto/WalletUtils.java
  core/src/main/java/org/web3j/protocol/core/DefaultBlockParameter.java
  core/src/main/java/org/web3j/protocol/http/HttpService.java
  core/src/main/java/org/web3j/protocol/websocket/WebSocketClient.java
  core/src/main/java/org/web3j/tx/Contract.java
  core/src/test/java/org/web3j/crypto/Bip44WalletUtilsTest.java
  core/src/test/java/org/web3j/crypto/WalletTest.java
  core/src/test/java/org/web3j/crypto/WalletUtilsTest.java
  core/src/test/java/org/web3j/protocol/websocket/WebSocketClientTest.java
  core/src/test/java/org/web3j/tx/ContractTest.java
  core/src/test/resources/keyfiles/UTC--2016-11-03T05-55-06.340672473Z--ef678007d18427e6022059dbc264f27507cd1ffc
  core/src/test/resources/keyfiles/UTC--2016-11-03T07-47-45.988Z--4f9c1a1efaa7d81ba1cabf07f2c3a5ac5cf4f818
  core/src/test/resources/keyfiles/readme.txt
  crypto/build.gradle
  crypto/src/main/java/org/web3j/crypto/Keys.java
  crypto/src/main/java/org/web3j/crypto/MnemonicUtils.java
  crypto/src/main/java/org/web3j/crypto/Sign.java
  docs/source/getting_started.rst
  gradle.properties
  pantheon/build.gradle
  pantheon/src/main/java/org/web3j/protocol/pantheon/JsonRpc2_0Pantheon.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/Pantheon.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/response/FullDebugTraceInfo.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/response/PantheonEthAccountsMapResponse.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/response/PantheonFullDebugTraceResponse.java
  pantheon/src/main/java/org/web3j/protocol/pantheon/response/StructLogs.java
  pantheon/src/test/java/org/web3j/protocol/pantheon/RequestTest.java
  pantheon/src/test/java/org/web3j/protocol/pantheon/ResponseTest.java
  settings.gradle
Labels: needs-ci-approvals
