Repository web3j/web3j, pull requests merged in 2019-08, with the labels that each got.

#901 Add ScheduledExecutorService to Parity constructor like in org/web3j/…
  parity/src/main/java/org/web3j/protocol/parity/JsonRpc2_0Parity.java
  parity/src/main/java/org/web3j/protocol/parity/Parity.java
Labels: merge-to-android

#976 Implemented ReadonlyTransactionManager sendCall
  core/src/main/java/org/web3j/tx/ReadonlyTransactionManager.java
  core/src/test/java/org/web3j/tx/ReadonlyTransactionManagerTest.java
Labels: needs-user-changes

#998 Stale bot
  .github/stale.yml
Labels: needs-review
