Repository web3j/web3j, pull requests merged in 2019-03, with the labels that each got.

#659 Added ERC20, ERC721 Contract
  console/build.gradle
  contracts/build.gradle
  contracts/scripts/generateWrappers.sh
  contracts/src/main/java/org/web3j/contracts/eip165/generated/ERC165.java
  contracts/src/main/java/org/web3j/contracts/eip20/generated/ERC20.java
  contracts/src/main/java/org/web3j/contracts/eip721/generated/ERC721.java
  contracts/src/main/java/org/web3j/contracts/eip721/generated/ERC721Enumerable.java
  contracts/src/main/java/org/web3j/contracts/eip721/generated/ERC721Metadata.java
  contracts/src/main/resources/eip165/solidity/ERC165.sol
  contracts/src/main/resources/eip20/solidity/ERC20.sol
  contracts/src/main/resources/eip721/solidity/ERC721.sol
  contracts/src/main/resources/eip721/solidity/ERC721Enumerable.sol
  contracts/src/main/resources/eip721/solidity/ERC721Metadata.sol
  docs/source/contracts.rst
  docs/source/index.rst
  docs/source/modules.rst
  settings.gradle
Labels: awaiting-android-release, awaiting-release

#878 skip metadata for validating contract code
  core/src/main/java/org/web3j/tx/Contract.java
  core/src/test/java/org/web3j/tx/ContractTest.java
Labels: awaiting-release, merge-to-android

#859 Retrieve revert reason for EthCall
  core/src/main/java/org/web3j/protocol/core/methods/response/EthCall.java
  core/src/test/java/org/web3j/protocol/core/ResponseTest.java
Labels: awaiting-release, merge-to-android

#797 Add contributing guidelines
  CONTRIBUTING.md
Labels: awaiting-release
