Repository web3j/web3j, pull requests merged in 2019-09, with the labels that each got.

#1008 Web3j new console features
  console/build.gradle
  console/src/main/java/org/web3j/console/Runner.java
  console/src/main/java/org/web3j/console/project/InteractiveImporter.java
  console/src/main/java/org/web3j/console/project/InteractiveOptions.java
  console/src/main/java/org/web3j/console/project/Project.java
  console/src/main/java/org/web3j/console/project/ProjectCreator.java
  console/src/main/java/org/web3j/console/project/ProjectCreatorCLIRunner.java
  console/src/main/java/org/web3j/console/project/ProjectImporter.java
  console/src/main/java/org/web3j/console/project/ProjectImporterCLIRunner.java
  console/src/main/java/org/web3j/console/project/ProjectStructure.java
  console/src/main/java/org/web3j/console/project/ProjectVisitor.java
  console/src/main/java/org/web3j/console/project/ProjectWriter.java
  console/src/main/java/org/web3j/console/project/TemplateProvider.java
  console/src/main/java/org/web3j/console/project/utills/InputVerifier.java
  console/src/main/resources/Greeter.sol
  console/src/main/resources/Template.java
  console/src/main/resources/build.gradle.template
  console/src/main/resources/gradle-wrapper.jar
  console/src/main/resources/gradlew-wrapper.properties.template
  console/src/main/resources/gradlew.bat.template
  console/src/main/resources/gradlew.template
  console/src/main/resources/settings.gradle.template
  console/src/test/java/org/web3j/console/project/InteractiveImporterTest.java
  console/src/test/java/org/web3j/console/project/InteractiveOptionsTest.java
  console/src/test/java/org/web3j/console/project/ProjectCreatorCLIRunnerTest.java
  console/src/test/java/org/web3j/console/project/ProjectCreatorTest.java
  console/src/test/java/org/web3j/console/project/ProjectImporterCLIRunnerTest.java
  console/src/test/java/org/web3j/console/project/ProjectImporterTest.java
  console/src/test/java/org/web3j/console/project/ProjectStructureTest.java
  console/src/test/java/org/web3j/console/project/ProjectTest.java
  console/src/test/java/org/web3j/console/project/ProjectWriterTest.java
  console/src/test/java/org/web3j/console/project/TemplateProviderTest.java
  console/src/test/java/org/web3j/console/project/utills/InputVerifierTest.java
  console/src/test/resources/Solidity/NestedSolidityFolder/NestedContract.sol
  console/src/test/resources/Solidity/NestedSolidityFolder/NestedContract2.sol
  console/src/test/resources/Solidity/TestContract.sol
  console/src/test/resources/Solidity/TestContract2.sol
Labels: needs-user-changes

#1014 Bugfix/web3j docs (#1013 close)
  docs/index.md
  docs/smart_contracts.md
Labels: needs-review

#1050 Build: fix warnings in TypeDecoder Class
  abi/src/main/java/org/web3j/abi/TypeDecoder.java
Labels: merge-to-android

#989 Fix and test for duplicated fields (#680)
  codegen/src/main/java/org/web3j/codegen/SolidityFunctionWrapper.java
  codegen/src/test/java/org/web3j/codegen/SolidityFunctionWrapperGeneratorTest.java
  codegen/src/test/resources/solidity/build.sh
  codegen/src/test/resources/solidity/duplicate/DuplicateField.sol
  codegen/src/test/resources/solidity/duplicate/build/DuplicateField.abi
  codegen/src/test/resources/solidity/duplicate/build/DuplicateField.bin
Labels: merge-to-android

#1010 add config loader from JSON string
  core/src/main/java/org/web3j/crypto/WalletUtils.java
  core/src/test/java/org/web3j/crypto/WalletUtilsTest.java
Labels: merge-to-android

#1042 [WIP] Update docs for web3j run/import
  docs/command_line_tools.md
  docs/quickstart.md
Labels: needs-review
